
import { PlaceHolderImages } from './placeholder-images';
import type { Product, Testimonial, Category } from './types';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) {
    // Return a default placeholder if not found to avoid crashing
    return { id: 'not-found', description: 'Image not found', imageUrl: 'https://picsum.photos/seed/notfound/800/1200', imageHint: 'placeholder' };
  }
  return image;
};

export const categories: Category[] = [
  {
    id: 'new-arrivals',
    name: 'New Arrivals',
    description: 'The latest styles to elevate your wardrobe.',
  },
  {
    id: 'luxury-formals',
    name: 'Luxury Formals',
    description: 'Exquisite designs for your most special occasions.',
  },
  {
    id: 'everyday-comfort',
    name: 'Everyday Comfort',
    description: 'Effortless pieces for your daily life.',
  },
];

const allProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Mannequin Dress',
    price: 350,
    category: 'new-arrivals',
    images: [findImage('product-1-1')],
    stock: 15,
    description: 'An elegant Pakistani dress displayed on a mannequin.',
    details: 'Full-length gown with intricate embroidery.',
    fabric: 'Chiffon',
    colors: ['Pastel Green'],
    rating: 4.8,
    reviewCount: 22,
  },
  {
    id: '2',
    name: 'Vibrant Textile Kurta',
    price: 220,
    category: 'everyday-comfort',
    images: [findImage('product-2-1')],
    stock: 25,
    description: 'A colorful kurta inspired by Pakistani textile markets.',
    details: 'Straight fit, round neck, and vibrant prints.',
    fabric: 'Cotton',
    colors: ['Multi-color'],
    rating: 4.6,
    reviewCount: 31,
  },
  {
    id: '3',
    name: 'Beige Shalwar Kameez',
    price: 180,
    category: 'everyday-comfort',
    images: [findImage('product-3-1')],
    stock: 40,
    description: 'A simple and versatile beige shalwar kameez for men.',
    details: 'Comfortable fit, perfect for work or casual outings.',
    fabric: 'Cotton',
    colors: ['Beige'],
    rating: 4.6,
    reviewCount: 33,
  },
  {
    id: '4',
    name: 'Royal Blue Kurta',
    price: 290,
    category: 'new-arrivals',
    images: [findImage('product-4-1')],
    stock: 19,
    description: 'A striking royal blue kurta for special occasions.',
    details: 'Silk fabric with a subtle sheen and minimalist design.',
    fabric: 'Silk',
    colors: ['Royal Blue'],
    rating: 4.7,
    reviewCount: 16,
  },
  {
    id: '5',
    name: 'Classic Black Waistcoat',
    price: 450,
    category: 'luxury-formals',
    images: [findImage('product-5-1')],
    stock: 25,
    description: 'A tailored black waistcoat to elevate any traditional outfit.',
    details: 'Textured fabric, six-button front, and a sharp cut.',
    fabric: 'Blended Fabric',
    colors: ['Classic Black'],
    rating: 4.8,
    reviewCount: 21,
  },
  {
    id: '6',
    name: 'Burgundy Shawl for Men',
    price: 350,
    category: 'new-arrivals',
    images: [findImage('product-6-1')],
    stock: 20,
    description: 'A warm and stylish burgundy shawl for men.',
    details: 'Soft wool blend with a classic, subtle pattern.',
    fabric: 'Wool Blend',
    colors: ['Burgundy'],
    rating: 4.7,
    reviewCount: 22,
  },
  {
    id: '7',
    name: 'Lemon Zest Kurti',
    price: 170,
    category: 'everyday-comfort',
    images: [findImage('product-7-1')],
    stock: 35,
    description: 'A fresh and bright yellow kurti for sunny days.',
    details: 'Light embroidery on the neckline, comfortable for daily wear.',
    fabric: 'Lawn',
    colors: ['Lemon Zest'],
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: '8',
    name: 'Opal White Angrakha',
    price: 950,
    category: 'new-arrivals',
    images: [findImage('product-8-1')],
    stock: 12,
    description: 'A traditional angrakha style dress in a beautiful opal white.',
    details: 'Tassel ties, flared cut, with delicate chikankari work.',
    fabric: 'Chikankari',
    colors: ['Opal White'],
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: '9',
    name: 'Forest Green Prince Coat',
    price: 1200,
    category: 'luxury-formals',
    images: [findImage('product-9-1')],
    stock: 10,
    description: 'A regal prince coat in a deep forest green.',
    details: 'Velvet fabric with subtle gold buttons and a tailored fit.',
    fabric: 'Velvet',
    colors: ['Forest Green'],
    rating: 4.8,
    reviewCount: 15,
  },
  {
    id: '10',
    name: 'Graphite Black Sherwani',
    price: 1800,
    category: 'luxury-formals',
    images: [findImage('product-10-1')],
    stock: 7,
    description: 'A sharp and elegant black sherwani for men.',
    details: 'Intricate self-embroidery, classic cut, with matching trousers.',
    fabric: 'Jamawar',
    colors: ['Graphite Black'],
    rating: 4.9,
    reviewCount: 11,
  },
  {
    id: '11',
    name: 'Fuchsia Dream Lehnga',
    price: 1500,
    category: 'luxury-formals',
    images: [findImage('product-11-1')],
    stock: 5,
    description: 'A vibrant fuchsia lehnga choli with mirror work.',
    details: 'Flared lehnga, embellished choli, and a matching net dupatta.',
    fabric: 'Raw Silk',
    colors: ['Fuchsia'],
    rating: 4.9,
    reviewCount: 9,
  },
  {
    id: '12',
    name: 'Artisan Weave Tunic',
    price: 200,
    category: 'everyday-comfort',
    images: [findImage('product-12-1')],
    stock: 30,
    description: 'A comfortable and stylish tunic with modern prints, inspired by artisan weaving.',
    details: 'Loose fit, boat neck, and three-quarter sleeves.',
    fabric: 'Linen',
    colors: ['Woven Blue'],
    rating: 4.6,
    reviewCount: 25,
  },
  {
    id: '13',
    name: 'Amber Gold Kurta',
    price: 310,
    category: 'new-arrivals',
    images: [findImage('product-13-1')],
    stock: 18,
    description: 'A rich amber gold kurta with traditional block print patterns.',
    details: 'Straight fit, round neck, and full sleeves.',
    fabric: 'Cotton Silk',
    colors: ['Amber Gold'],
    rating: 4.8,
    reviewCount: 17,
  },
  {
    id: '14',
    name: 'Azure Dreams Saree',
    price: 850,
    category: 'luxury-formals',
    images: [findImage('product-14-1')],
    stock: 11,
    description: 'A captivating azure blue saree with silver sequin work.',
    details: 'Flowy chiffon fabric with a fully embellished border.',
    fabric: 'Chiffon',
    colors: ['Azure Blue'],
    rating: 4.8,
    reviewCount: 19,
  },
  {
    id: '15',
    name: 'Ivory Elegance Kurta',
    price: 620,
    category: 'new-arrivals',
    images: [findImage('product-15-1')],
    stock: 14,
    description: 'An ivory white kurta featuring intricate threadwork.',
    details: 'A-line cut with detailed embroidery on the sleeves and daman.',
    fabric: 'Cotton Net',
    colors: ['Ivory White'],
    rating: 4.9,
    reviewCount: 23,
  }
];

export const products: Product[] = allProducts.filter(p => p.images.every(img => img.id !== 'not-found'));

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sophia Chen',
    handle: '@sophia_c',
    quote: "Elysian Threads is my go-to for timeless pieces. The quality is unmatched and the designs are so elegant. I feel beautiful in everything I wear from them.",
    avatar: findImage('testimonial-1'),
  },
  {
    id: '2',
    name: 'Isabella Rossi',
    handle: '@isabella.rossi',
    quote: "The customer service is as premium as the clothes. My order arrived beautifully packaged and the fit was perfect. It's an experience, not just a purchase.",
    avatar: findImage('testimonial-2'),
  },
  {
    id: '3',
    name: 'Ava Nguyen',
    handle: '@avan',
    quote: 'Finally, a brand that understands minimalist luxury. The fabrics feel incredible and the minimalist aesthetic is exactly what I\'ve been looking for.',
    avatar: findImage('testimonial-3'),
  },
];
