// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
//
// To use this file outside of Firebase Studio, you will need to
// replace the auto-generated config with your own.

// Get this from the Firebase console.
const firebaseConfig = {
    "apiKey": "AIzaSyBn6qZFh-ufhtT1Yq-qAbR0BY_Jt_P_MoE",
    "authDomain": "elysianthreads-e8f8b.firebaseapp.com",
    "projectId": "elysianthreads-e8f8b",
    "storageBucket": "elysianthreads-e8f8b.appspot.com",
    "messagingSenderId": "390747323215",
    "appId": "1:390747323215:web:e5457af5d3ab43de90633a",
    "measurementId": "G-P33PJ8XTP7"
};

export function getFirebaseConfig() {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error('No Firebase configuration object provided.' + '\n' +
      'Add your web app\'s configuration object to firebase-config.ts');
  } else {
    return firebaseConfig;
  }
}
